version: "3.9"

services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5432:5432"

  sleep_api:
    build: ./sleep/.
    volumes:
      - ./sleep/:/sleep/
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
